nacos:
  config:
    data-id: LEARN_DEV
    server-addr: localhost:8848
    group: DEFAULT_GROUP
    namespace: 88f0fe69-7993-43d3-b850-ca2060393cc3
    bootstrap:
      enable: true
    username: nacos
    password: nacos


